name: OpenDoor

volumes:
  dbdata:

services:
  php:
    image: opendoor-php
    build:
      context: .
      dockerfile: php.Dockerfile

    # Split mounts to prevent hiding of preexisting ./vendor/ in image
    volumes:
      - ./public:/var/www/public:ro # source files
      - ./pages:/var/www/pages:ro
      - ./classes:/var/www/classes:ro
      - ./includes:/var/www/includes:ro
      - ./config/:/var/www/config:rw # config files are editable
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: opendoor-mysql
    build:
      dockerfile_inline: |
        FROM mysql:8.4
    environment:
      MYSQL_DATABASE: OpenDoor
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - dbdata:/var/lib/mysql:rw # database data (tables and config)
      - ./database/scripts/:/docker-entrypoint-initdb.d/:ro # sql scripts, executed in alphabetical order
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf:ro # config for correct string encoding
